---
# tasks file for package_remove
- name: Patching for packages
  yum:
    name: "*"
    state: latest
  when: (ansible_distribution == "CentOS") or (ansible_distribution == "RedHat")
  notify:
    - reboot_node
