---
# tasks file for package_remove
- name: Install packages for particular OS
  yum:
    name: "{{ packages }}"
    state: present
  when: (ansible_distribution == "CentOS") or (ansible_distribution == "RedHat")